Question 1

In [1]:
# takes type and then the actual value to be printed finally then converts accordingly and returns it
def convertLength(x,type):
  if (type=="meters"):
    result=x*3.28
  elif(type=="feet"):
    result=x/3.28
  return result

# takes weight and the type and converts accordingly and returns it
def convertWeight(x,type):
  if (type=="kilograms"):
    result=x*2.20
  elif(type=="pounds"):
    result=x/2.20
  return result

# takes volume and the type and converts accordingly and returns it
def convertVolume(x,type):
  if (type=="liters"):
    result=x*3.78
  elif(type=="gallons"):
    result=x/3.78
  return result

In [2]:
conversion=input("Enter the type of conversion: length, weight, volume")
a=input("Enter the value to be converted: ")
try:
    a=int(a)
except:
    print("Invalid input")
type=input("Enter the type of value your entered: meters,feet,kilograms,pounds,liters,gallons")
match conversion:
  case "length":
    print(convertLength(a,type))
  case "weight":
    print(convertWeight(a,type))
  case "volume":
    print(convertVolume(a,type))

Enter the type of conversion: length, weight, volumelength
Enter the value to be converted: 4
Enter the type of value your entered: meters,feet,kilograms,pounds,liters,gallonsmeters
13.12


Question 2

In [3]:
def sum(x):
  # takes a parameter list and provides the sum of the elements of list
  result=0
  for x in x:
    result+=x
  return result

def average(x):
  # takes a parameter list and returns the average of the elements
  result=0
  for x in x:
    sum+=x
  result=sum/len(x)
  return result

def maximum(x):
  # takes a parameter list and returns the maximum of the elements
  return max(x)

def minimum(x):
  # takes a parameter list and returns the maximum of the elements
  return min(x)


In [6]:
a=input("enter list separated by spaces")
try:
  list=[int(x) for x in a if x.isnumeric()]
except:
  print("Enter valid numbers")
operation=input("Enter operation: sum, average,maximum,minimum")
match operation:
  case "sum":
    print(sum(list))
  case "average":
    print(average(list))
  case "maximum":
    print(maximum(list))
  case "minimum":
    print(minimum(list))


enter list separated by spaces3 4 5
Enter operation: sum, average,maximum,minimumsum
12


Question 3

In [5]:
def extract_every_other(lst):
  new_list=[x for index,x in enumerate(lst) if index%2==0]
  return new_list

print(extract_every_other([1,2,3,4,5,6]))


[1, 3, 5]


Question 4

In [7]:
def get_sublist(lst,start,end):
  new_list=lst[start:end+1]
  return new_list

print(get_sublist([1,2,3,4,5,6],2,4))


[3, 4, 5]


Question 5

In [8]:
def reverse_list(lst):
  new_list=lst[::-1]
  return new_list

print(reverse_list([1,2,3,4,5,6]))

[6, 5, 4, 3, 2, 1]


Question 6

In [9]:
def remove_first_last(lst):
  new_list=lst[1:len(lst)-1]
  return new_list

print(remove_first_last([1,2,3,4,5]))


[2, 3, 4]


Question 7

In [10]:
def get_first_n(lst,n):
  new_list=lst[:n]
  return new_list

print(get_first_n([1,2,3,4,5],3))


[1, 2, 3]


Question 8

In [11]:
def get_last_n(lst,n):
  new_list=lst[len(lst)-n:]
  return new_list

print(get_last_n([1,2,3,4,5],2))

[4, 5]


Question 9

In [ ]:
def reverse_skip(lst):
  new_list=lst[::-1]
  new_list=new_list[1::2]
  return new_list

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


Question 10

In [ ]:
def flatten(lst):
  new_list=[]
  for x in lst:
    for y in x:
      new_list.append(y)
  return new_list

print(flatten([[1,2,3],[4,5,6]]))

[1, 2, 3, 4, 5, 6]


Question 11

In [ ]:
def access_nested_element(lst,indices):
  for index in indices:
    lst=lst[index]
  return lst

print(access_nested_element([[1,2,3],[4,5,6],[7,8,9]],[1,2]))


6


Question 12

In [ ]:
def sum_nested(lst):
  sum=0
  for x in lst:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            sum+=z
        else:
          sum+=y
    else:
      sum+=x
  return sum

print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


Question 13


In [ ]:
def remove_element(lst,elem):
  for x in lst:
    for y in x:
      if(y==elem):
        x.remove(y)
  return lst

print(remove_element([[1, 2], [3, 2], [4, 5]],2))

[[1], [3], [4, 5]]


Question 14

In [ ]:
def find_max(lst):
  max=0
  for x in lst:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            if(z>max):
              max=z
        else:
          if(y>max):
            max=y
    else:
      if(x>max):
        max=x
  return max

print(find_max([[1, 2], [3, [4, 5]], 6]))


6


Question 15

In [ ]:
def count_occurences(lst,elem):
  count=0
  for x in lst:
    for y in x:
      if(y==elem):
        count+=1
  return count

print(count_occurences([[1, 2], [3, 2], [4, 2]],2))


3


Question 16

In [ ]:
def deep_flatten(lst):
  new_list=[]
  for x in lst:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            new_list.append(z)
        else:
          new_list.append(y)
    else:
      new_list.append(x)

  return new_list

print(deep_flatten([[1, 2], [3, [4, 5]], 6]))

[1, 2, 3, 4, 5, 6]


Question 17

In [ ]:
def average_nested(lst):
  avg=0
  sum=0
  length=0
  for x in lst:
    for y in x:
      sum+=y
      length+=1
  avg=sum/length
  return avg

print(average_nested([[1, 2], [3, 4], [5, 6]]))


3.5


Question 18

In [ ]:
import numpy as np

In [ ]:
empty_arr=np.empty(2)
one_arr=np.ones((4,2))
full_arr=np.full((2,3),5)
zerolikearr=np.zeros_like(one_arr)
onelikearr=np.ones_like(one_arr)
lstarr=np.array([1,2,3,4])
print(empty_arr)
print(one_arr)
print(full_arr)
print(zerolikearr)
print(onelikearr)
print(lstarr)



[-5.73021895e-300  6.54049975e-310]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4]


Question 19

In [ ]:
range_arr=np.arange(10,49)
matrix=np.arange(0,9).reshape((3,3))
eye_matrix=np.eye(3)
rand=np.random.random((3,3))
mean=rand.mean()
rand1=np.random.random((10,10))
max=rand1.max()
min=rand1.min()
zeroarr=np.zeros((10,10))
zeroarr[6]=1
arr=[1,2,0,0,4,0]
reversearr=arr[::-1]
arrborder=np.zeros((3,3))
arrborder[0,:]=1
arrborder[:,0]=1
arrborder[:,-1]=1
arrborder[-1,:]=1
checkerboard=np.zeros((8,8))
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(range_arr)
print(matrix)
print(eye_matrix)
print(rand)
print(mean)
print(rand1)
print(max)
print(min)
print(zeroarr)
print(reversearr)
print(arrborder)
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.98621525 0.99915472 0.01838065]
 [0.78399331 0.21621323 0.03259458]
 [0.49511489 0.55488381 0.79319139]]
0.5421935376030816
[[0.80860345 0.03737952 0.59679581 0.15025111 0.06698502 0.14504062
  0.33189682 0.85117438 0.94033522 0.57451972]
 [0.58744844 0.95677891 0.49874951 0.89845742 0.46705278 0.72301887
  0.80850946 0.62900679 0.65563079 0.63730134]
 [0.4207448  0.06010846 0.30458785 0.81218331 0.98252925 0.57922605
  0.89752698 0.26444644 0.60811324 0.93163009]
 [0.59169156 0.96050685 0.21076251 0.00902767 0.29394886 0.21147776
  0.72459875 0.8117464  0.49862743 0.44644808]
 [0.21398143 0.83403915 0.00733714 0.56301526 0.44570635 0.25766568
  0.72742914 0.07556939 0.33038958 0.23602214]
 [0.5971922  0.96073937 0.38532823 0.19806744 0.11149716 0.23201635
  0.93938165 0.77111949 0.98903258 0.1654932

Question 20

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum=np.add(x,y)
sub=np.subtract(x,y)
multiply=np.multiply(x,y)
square=np.square(x)
vdotw=np.dot(v,w)
xdotv=np.dot(x,v)
xdoty=np.dot(x,y)
rowconcat=np.concatenate((x,y),axis=0)
columnconcat=np.concatenate((x,y),axis=1)
print(sum)
print(sub)
print(multiply)
print(square)
print(vdotw)
print(xdotv)
print(xdoty)
print(rowconcat)
print(columnconcat)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 5 12]
 [21 40]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 5 7 8]]


Question 21

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
ainverse=np.linalg.inv(A)
eye=A@ainverse
AB=np.matmul(A,B)
BA=np.matmul(B,A)
At=np.transpose(A)
Bt=np.transpose(B)
ABt=np.transpose(AB)
BtAt=np.matmul(Bt,At)
print(eye)
print(AB)
print(BA)
print(ABt)
print(BtAt)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
